// Generated by https://quicktype.io

export interface CreateUserResponse {
    email: string;
    _id: string;
    name: string;
    roles: string[];
    isBanned: boolean;
    isActive: boolean;
    isVerified: boolean;
}
