// Generated by https://quicktype.io

export interface User {
    email?: string;
    _id?: string;
    name?: string;
    bio?: string;
    linkedin?: string;
    roles?: string[];
    isBanned?: boolean;
    isActive?: boolean;
    isVerified?: boolean;
    password?: string;
}
